### ISSUE TITLE
Cannot build on Windows with GHC 9.8.4

### ISSUE THREAD

**Issue by clin1234** [haskell-pkg-janitors/unix-compat#13]
```
unix-compat                        > hsc2hs-ghc-9.8.4.exe: fd:3: hGetContents: invalid argument (cannot decode byte sequence starting from 233)
```

Even though `chcp` shows `65001` i.e. UTF-8.

**Comment by andreasabel** [comment]
At least with Stackage LTS-23.0 (GHC 9.8.4) it does build under Windows: https://github.com/haskell-pkg-janitors/unix-compat/actions/runs/12291436532/job/34300207381?pr=14#step:12:65

Is it only 9.8.4, or also e.g., 9.8.2?

**Comment by andreasabel** [comment]
For now, I consider this an upstream problem:
- https://github.com/commercialhaskell/stack/issues/6670
